GAIterationScript
save('D:\Users\teagu\Documents\GitHub\VorMod\MATLAB\Results\20180731T222915\_postGA.mat')
clearvars
load('D:\Users\teagu\Documents\GitHub\VorMod\MATLAB\Results\20180728T140602\_postGA.mat')
GAIterationScript
save('D:\Users\teagu\Documents\GitHub\VorMod\MATLAB\Results\20180728T140602\_postGA2.mat')
clearvars
load('D:\Users\teagu\Documents\GitHub\VorMod\MATLAB\Results\20180730T214611\_postGA.mat')
GAIterationScript
save('D:\Users\teagu\Documents\GitHub\VorMod\MATLAB\Results\20180730T214611\_postGA2.mat')
% GA_BETA = [0.5:0.1:1 1.5:0.5:2.5];
% GA_BETA_LENGTH = length(GA_BETA);
% GAIterationScript
% save('_postGA.mat')
% clearvars
% load('D:\Users\teagu\Documents\GitHub\VorMod\MATLAB\Results\20180730T214611\tmp.mat')
% GA_BETA = 0.5:0.5:2.5;
% GA_BETA_LENGTH = length(GA_BETA);
% for iter = 1:GA_BETA_LENGTH
% 	VorModGASolutions(iter) = GeneticAlgorithmSolution;
% end
% VorModGA = VorModGeneticAlgorithm(GA_NUM_GENERATION_MEMBERS,    ...
%     FIELD_NUM_BASE_STATIONS, Field, ...
%     'beta', GA_BETA(1), ...
%     'range', FITNESS_OVERRANGE_COST,    ...
%     'capacity', FITNESS_OVERCAPACITY_COST,  ...
%     'elite', GA_NUM_GENERATION_ELITISM, ...
%     'unique', GA_UNIQUENESS,    ...
%     'crossover', GA_CROSSOVER_RATE, ...
%     'mutation', GA_MUTATION_RATE,   ...
%     'fitcount', GA_NUM_FITNESS_HALT,    ...
%     'memcount', GA_NUM_MEMBER_HALT, ...
%     'generationreport', CTRL_GENERATION_REPORT, ...
%     'graph', 0,  ...
%     'min', GA_NUM_MINIMUM_GENERATIONS,  ...
%     'max', GA_NUM_MAXIMUM_GENERATIONS);
% GAIterationScript
% save('D:\Users\teagu\Documents\GitHub\VorMod\MATLAB\Results\20180730T214611\_postGA.mat')
% clearvars
% load('D:\Users\teagu\Documents\GitHub\VorMod\MATLAB\Results\20180731T222915\tmp.mat')
% GA_BETA = 0.5:0.5:2.5;
% GA_BETA_LENGTH = length(GA_BETA);
% for iter = 1:GA_BETA_LENGTH
% 	VorModGASolutions(iter) = GeneticAlgorithmSolution;
% end
% VorModGA = VorModGeneticAlgorithm(GA_NUM_GENERATION_MEMBERS,    ...
%     FIELD_NUM_BASE_STATIONS, Field, ...
%     'beta', GA_BETA(1), ...
%     'range', FITNESS_OVERRANGE_COST,    ...
%     'capacity', FITNESS_OVERCAPACITY_COST,  ...
%     'elite', GA_NUM_GENERATION_ELITISM, ...
%     'unique', GA_UNIQUENESS,    ...
%     'crossover', GA_CROSSOVER_RATE, ...
%     'mutation', GA_MUTATION_RATE,   ...
%     'fitcount', GA_NUM_FITNESS_HALT,    ...
%     'memcount', GA_NUM_MEMBER_HALT, ...
%     'generationreport', CTRL_GENERATION_REPORT, ...
%     'graph', 0,  ...
%     'min', GA_NUM_MINIMUM_GENERATIONS,  ...
%     'max', GA_NUM_MAXIMUM_GENERATIONS);
% GAIterationScript
% save('D:\Users\teagu\Documents\GitHub\VorMod\MATLAB\Results\20180731T222915\_postGA.mat')